Updated Quadhoral openmeteo pipeline readme
AlexOBarnes/StarWatch pull request #197
Opened 2024-10-11 10:57 UTC by AlexOBarnes

This closes #120 

What I have done:
Updated the readme for the quadhoral Openmeteo pipeline

2024-10-11 14:45 UTC, CalebMathers approved these changes

2024-10-11 14:45 UTC, CalebMathers commented on quadhoral-openmeteo/README.md
> +### To Run on AWS:
Good headings overall

2024-10-11 14:45 UTC, CalebMathers commented on quadhoral-openmeteo/README.md
> +#### `conftest.py`
Incredible use of markdown

2024-10-11 14:45 UTC, CalebMathers commented on quadhoral-openmeteo/README.md
> +```bash
Good to have these commands in code blocks for easy copying

2024-10-11 14:45 UTC, CalebMathers commented on quadhoral-openmeteo/README.md
> +4. Verify your credentials:
Verifying credentials is one of my favourite things to do

2024-10-13 17:10 UTC, olliejth commented on quadhoral-openmeteo/README.md
> +- Contains the `pytest.fixture` functions for the tests in this folder.
A worthwhile addition, this will be useful to any developers working on this project in the future.

2024-10-13 17:10 UTC, olliejth commented on quadhoral-openmeteo/README.md
>  This folder contains the code for the [OpenMeteo API](https://open-meteo.com/en/docs) data pipeline. This includes `extract.py`, `transform.py`, `load.py` and `pipeline.py`. This pipeline uses the `r
Is this one long line in the code?

2024-10-13 17:11 UTC, olliejth commented on quadhoral-openmeteo/README.md
> +7. Now follow the terraform setup steps in the `../terraform` folder to provision a lambda based off this docker image.
Nice code blocks for clarity and general presentation.

2024-10-13 17:17 UTC, olliejth commented on quadhoral-openmeteo/README.md
> +#### `conftest.py`
We love subheadings.

2024-10-13 17:19 UTC, olliejth commented on quadhoral-openmeteo/README.md
> +2. Setup a venv and install the requirements
Missing full-stops after 1 and 2.

2024-10-14 08:11 UTC, olliejth requested changes
Some missing full-stops.

2024-10-14 08:53 UTC, AlexOBarnes commented on quadhoral-openmeteo/README.md
> +2. Setup a venv and install the requirements
```suggestion
1. Ensure that an SQL server RDS has been setup prior and is accessible.
    - Note: be sure to store the credentials for accessing this database safely.

### To Run Locally:
2. Setup a venv and install the requirements.
```

2024-10-14 08:55 UTC, olliejth approved these changes
Changes made, approved.

2024-10-14 08:55 UTC, merged