Updated readme
AlexOBarnes/StarWatch pull request #198
Opened 2024-10-11 11:19 UTC by AlexOBarnes

This closes #123

What I have done:
- Updated readme for the astronomy pipeline

2024-10-13 17:21 UTC, olliejth commented on astronomy-pipeline/README.md
> +    - ASTRONOMY_SECRET - secret key used for accessing the astronomy API
NEVER

2024-10-13 17:22 UTC, olliejth commented on astronomy-pipeline/README.md
> +#### `db_connect.sh`
Good consistent formatting in having these file name headings all next to one another.

2024-10-13 17:22 UTC, olliejth commented on astronomy-pipeline/README.md
> +2. Signup for the [Astronomy API](https://astronomyapi.com/auth/signup) and store the id and secret key you receive securely
Nice addition of the API link.

2024-10-13 17:23 UTC, olliejth commented on astronomy-pipeline/README.md
> +2. Signup for the [Astronomy API](https://astronomyapi.com/auth/signup) and store the id and secret key you receive securely
Missing full-stops after 1 + 2 bullet points.

2024-10-14 08:13 UTC, olliejth requested changes
Check for missing full stops.

2024-10-14 08:51 UTC, AlexOBarnes commented on astronomy-pipeline/README.md
> +2. Signup for the [Astronomy API](https://astronomyapi.com/auth/signup) and store the id and secret key you receive securely
```suggestion
2. Signup for the [Astronomy API](https://astronomyapi.com/auth/signup) and store the id and secret key you receive securely.
```

2024-10-14 08:52 UTC, AlexOBarnes commented on astronomy-pipeline/README.md
> +1. Ensure that an SQL server RDS has been setup prior and is accessible
```suggestion
1. Ensure that an SQL server RDS has been setup prior and is accessible.
```

2024-10-14 08:55 UTC, olliejth approved these changes
Changes made, approved.

2024-10-14 08:55 UTC, merged