Add nasa images
AlexOBarnes/StarWatch pull request #234
Opened 2024-10-14 13:57 UTC by AlexOBarnes

This closes #233 

- Written tests for ISS api function
- Implemented ISS api function

2024-10-14 14:46 UTC, AlexOBarnes commented on dashboard/test_image_pipeline.py
> +        expected_result = {'timestamp': dt(2024,10,14,13,26,12),
```suggestion
        expected_result = {'timestamp': dt(2024,10,14,12,26,12),
```

2024-10-14 15:15 UTC, olliejth commented on dashboard/image_pipeline.py
> -    nasa_pipeline()
Nice work keeping the scripts clean.

2024-10-14 15:16 UTC, olliejth commented on dashboard/image_pipeline.py
> +    response = get(url, timeout=10)
Very elegant.

2024-10-14 15:17 UTC, olliejth commented on dashboard/image_pipeline.py
Clean and efficient.

2024-10-14 15:18 UTC, olliejth commented on dashboard/test_image_pipeline.py
>  NASA_API_URL = 'https://api.nasa.gov/planetary/apod?api_key=YOUR_API_KEY'
Do you need to remove "YOUR_API_KEY" from this?

2024-10-14 15:20 UTC, olliejth commented on dashboard/test_image_pipeline.py
>  NASA_API_URL = 'https://api.nasa.gov/planetary/apod?api_key=YOUR_API_KEY'
Is this used anywhere in the test file?

2024-10-14 15:23 UTC, olliejth requested changes
Left some comments on dashboard/test_image_pipeline.py. May not be an issue but worth a check.

2024-10-14 15:37 UTC, AlexOBarnes commented
Yeah, I see what your saying, it is used to mock the api call in some of the previous tests that weren't changed in this PR

2024-10-15 08:06 UTC, MurasatoNaoya commented on dashboard/image_pipeline.py
> +sys.path.append(os.path.abspath(os.path.join(
A good way of reducing redundancy, not having to copy an existing module.

2024-10-15 08:08 UTC, MurasatoNaoya commented on dashboard/test_image_pipeline.py
> +    @patch('image_pipeline.get')
Good use of patching to to interact with the actual ISS API.

2024-10-15 08:08 UTC, MurasatoNaoya approved these changes
LGTM.

2024-10-15 08:11 UTC, olliejth approved these changes
Changes explained and resolved.

2024-10-15 08:11 UTC, merged