Added precipitation visualisations, and formatted Weather page.
AlexOBarnes/StarWatch pull request #253
Opened 2024-10-15 15:34 UTC by MurasatoNaoya

Added the fourth and final visualisation for the Weather page, for precipitation likelihood (%) and precipitation level (mm). Both weather indicators are plotted on separate x-axes, on a y-axis of time. All weather visualisations are also formatted into two separate columns holding two visualisations each.

2024-10-15 17:58 UTC, AlexOBarnes requested changes
Need to remove commented out code

2024-10-15 17:58 UTC, AlexOBarnes commented on dashboard/dashboard.py
> +    #                     scale=alt.Scale(domain=[0, 30000],
Remove commented code

2024-10-15 17:58 UTC, AlexOBarnes commented on dashboard/load_dashboard_data.py
> +    = af.at;
What a beautiful query

2024-10-15 17:58 UTC, AlexOBarnes commented on dashboard/load_dashboard_data.py
> +        return max(0, min(sigmoid_coefficient, 1))
Patent this

2024-10-16 08:27 UTC, olliejth commented on dashboard/dashboard.py
> +    #                     scale=alt.Scale(domain=[0, 30000],
REMOVE!!!!!!!

2024-10-16 08:28 UTC, olliejth commented on dashboard/dashboard.py
Nice naming.

2024-10-16 08:29 UTC, olliejth commented on dashboard/dashboard.py
> +            filtered_df['precipitation_mm_rolling'] = filtered_df['precipitation_mm'].rolling(window=24).mean()
Nice use of rolling.

2024-10-16 08:29 UTC, AlexOBarnes approved these changes
thanks for making those changes

2024-10-16 08:29 UTC, AlexOBarnes commented on dashboard/dashboard.py
> +        precipitation_chart = alt.layer(
Love layering

2024-10-16 08:29 UTC, olliejth commented on dashboard/hold.py
> +        height=500,
Good idea to specify this 🥇

2024-10-16 08:31 UTC, olliejth commented on dashboard/load_dashboard_data.py
> +    = af.at;
Aaaaarrgghhh 😨

2024-10-16 08:33 UTC, olliejth commented on dashboard/load_dashboard_data.py
> +        print('No data fetched. Exiting.')
Exciting

2024-10-16 08:34 UTC, olliejth commented on dashboard/load_dashboard_data.py
> +        print('No data fetched. Exiting.')
This should be done using logging. 🌴

2024-10-16 08:34 UTC, olliejth commented on dashboard/requirements.txt
> +requests
Nice replacement.

2024-10-16 08:36 UTC, olliejth approved these changes
Large sections of commented out code. Logging should be implemented instead of print statements.

2024-10-16 08:40 UTC, merged